# Project-wide Gradle settings.

# Paralel build aktif (derleme süresi kısalır)
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true

# Android Gradle Plugin
android.useAndroidX=true
android.nonTransitiveRClass=true

# Kotlin — stdlib'i otomatik ekle
kotlin.stdlib.default.dependency=true

# Compose derleyici metrics (isteğe bağlı debug)
# android.enableComposeCompilerMetrics=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
