// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: mesh_packet.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Afet.Mesh {

  /// <summary>Holder for reflection information generated from mesh_packet.proto</summary>
  public static partial class MeshPacketReflection {

    #region Descriptor
    /// <summary>File descriptor for mesh_packet.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MeshPacketReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFtZXNoX3BhY2tldC5wcm90bxIJYWZldC5tZXNoIl0KCk1lc2hQYWNrZXQS",
            "IQoGaGVhZGVyGAEgASgLMhEuYWZldC5tZXNoLkhlYWRlchIZChFlbmNyeXB0",
            "ZWRfcGF5bG9hZBgCIAEoDBIRCglzaWduYXR1cmUYAyABKAwi5QEKBkhlYWRl",
            "chISCgptZXNzYWdlX2lkGAEgASgMEhcKD3RpbWVzdGFtcF9lcG9jaBgCIAEo",
            "DRILCgN0dGwYAyABKA0SEQoJaG9wX2NvdW50GAQgASgNEioKC3BhY2tldF90",
            "eXBlGAUgASgOMhUuYWZldC5tZXNoLlBhY2tldFR5cGUSGQoRc2VuZGVyX3B1",
            "YmxpY19rZXkYBiABKAwSHAoUcmVjaXBpZW50X3B1YmxpY19rZXkYByABKAwS",
            "FgoOcGF5bG9hZF9sZW5ndGgYCCABKA0SEQoJaG9wX3RyYWNlGAkgAygMIo8C",
            "ChBFbWVyZ2VuY3lQYXlsb2FkEhMKC2xhdGl0dWRlX2U2GAEgASgREhQKDGxv",
            "bmdpdHVkZV9lNhgCIAEoERISCgphY2N1cmFjeV9tGAMgASgNEhIKCmFsdGl0",
            "dWRlX20YBCABKBESEgoKaXNfdHJhcHBlZBgFIAEoCBISCgppc19pbmp1cmVk",
            "GAYgASgIEhQKDGlzX2NvbnNjaW91cxgHIAEoCBIUCgxwZW9wbGVfY291bnQY",
            "CCABKA0SEwoLYmF0dGVyeV9wY3QYCSABKA0SFAoMbWVzc2FnZV90ZXh0GAog",
            "ASgJEhIKCmJsb29kX3R5cGUYCyABKAkSFQoNbWVkaWNhbF9ub3RlcxgMIAEo",
            "CSJmChFBbnRpRW50cm9weURpZ2VzdBIZChFrbm93bl9tZXNzYWdlX2lkcxgB",
            "IAMoDBIeChZoYXNfZ2F0ZXdheV9jb25uZWN0aW9uGAIgASgIEhYKDnNlbmRl",
            "cl9ub2RlX2lkGAMgASgMInoKCUFja1BhY2tldBIYChBhY2tlZF9tZXNzYWdl",
            "X2lkGAEgASgMEhcKD2dhdGV3YXlfbm9kZV9pZBgCIAEoDBIaChJkZWxpdmVy",
            "eV9ob3BfY291bnQYAyABKA0SHgoWZXN0aW1hdGVkX3Jlc2N1ZV9lcG9jaBgE",
            "IAEoDSp1CgpQYWNrZXRUeXBlEgsKB1VOS05PV04QABIQCgxDUklUSUNBTF9T",
            "T1MQARIPCgtNRURJQ0FMX0FJRBACEg8KC0ZBTUlMWV9TQUZFEAMSEwoPUkVM",
            "QVlfSEVBUlRCRUFUEAQSEQoNQUNLX0RFTElWRVJFRBAFYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Afet.Mesh.PacketType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Afet.Mesh.MeshPacket), global::Afet.Mesh.MeshPacket.Parser, new[]{ "Header", "EncryptedPayload", "Signature" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Afet.Mesh.Header), global::Afet.Mesh.Header.Parser, new[]{ "MessageId", "TimestampEpoch", "Ttl", "HopCount", "PacketType", "SenderPublicKey", "RecipientPublicKey", "PayloadLength", "HopTrace" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Afet.Mesh.EmergencyPayload), global::Afet.Mesh.EmergencyPayload.Parser, new[]{ "LatitudeE6", "LongitudeE6", "AccuracyM", "AltitudeM", "IsTrapped", "IsInjured", "IsConscious", "PeopleCount", "BatteryPct", "MessageText", "BloodType", "MedicalNotes" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Afet.Mesh.AntiEntropyDigest), global::Afet.Mesh.AntiEntropyDigest.Parser, new[]{ "KnownMessageIds", "HasGatewayConnection", "SenderNodeId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Afet.Mesh.AckPacket), global::Afet.Mesh.AckPacket.Parser, new[]{ "AckedMessageId", "GatewayNodeId", "DeliveryHopCount", "EstimatedRescueEpoch" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// ─────────────────────────────────────────────────────────────────────
  /// PAKET TİPİ / ÖNCELİK SINIFI
  /// ─────────────────────────────────────────────────────────────────────
  /// </summary>
  public enum PacketType {
    [pbr::OriginalName("UNKNOWN")] Unknown = 0,
    /// <summary>
    /// Enkaz altı / Can tehlikesi — Asla düşürülmez (TTL yok sayılır)
    /// </summary>
    [pbr::OriginalName("CRITICAL_SOS")] CriticalSos = 1,
    /// <summary>
    /// Tıbbi yardım ihtiyacı
    /// </summary>
    [pbr::OriginalName("MEDICAL_AID")] MedicalAid = 2,
    /// <summary>
    /// "Güvendeyim" / Aile mesajı
    /// </summary>
    [pbr::OriginalName("FAMILY_SAFE")] FamilySafe = 3,
    /// <summary>
    /// Kurye sağlık durumu telsiz pingleri
    /// </summary>
    [pbr::OriginalName("RELAY_HEARTBEAT")] RelayHeartbeat = 4,
    /// <summary>
    /// Kurtarma merkezinden gelen "Ulaştı" teyidi
    /// </summary>
    [pbr::OriginalName("ACK_DELIVERED")] AckDelivered = 5,
  }

  #endregion

  #region Messages
  /// <summary>
  /// ─────────────────────────────────────────────────────────────────────
  /// TEMEL SOS / MESH PAKETI
  /// ─────────────────────────────────────────────────────────────────────
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MeshPacket : pb::IMessage<MeshPacket>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MeshPacket> _parser = new pb::MessageParser<MeshPacket>(() => new MeshPacket());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MeshPacket> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Afet.Mesh.MeshPacketReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MeshPacket() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MeshPacket(MeshPacket other) : this() {
      header_ = other.header_ != null ? other.header_.Clone() : null;
      encryptedPayload_ = other.encryptedPayload_;
      signature_ = other.signature_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MeshPacket Clone() {
      return new MeshPacket(this);
    }

    /// <summary>Field number for the "header" field.</summary>
    public const int HeaderFieldNumber = 1;
    private global::Afet.Mesh.Header header_;
    /// <summary>
    /// ── Yönlendirme Başlığı (Ara düğümler tarafından okunabilir, açık) ──
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Afet.Mesh.Header Header {
      get { return header_; }
      set {
        header_ = value;
      }
    }

    /// <summary>Field number for the "encrypted_payload" field.</summary>
    public const int EncryptedPayloadFieldNumber = 2;
    private pb::ByteString encryptedPayload_ = pb::ByteString.Empty;
    /// <summary>
    /// ── Şifreli Yük (Ara düğümler tarafından okunamaz - Curve25519 ECDH + XSalsa20-Poly1305) ──
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString EncryptedPayload {
      get { return encryptedPayload_; }
      set {
        encryptedPayload_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "signature" field.</summary>
    public const int SignatureFieldNumber = 3;
    private pb::ByteString signature_ = pb::ByteString.Empty;
    /// <summary>
    /// ── Gönderenin Ed25519 imzası (Header + encrypted_payload üzerinden) ──
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Signature {
      get { return signature_; }
      set {
        signature_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MeshPacket);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MeshPacket other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Header, other.Header)) return false;
      if (EncryptedPayload != other.EncryptedPayload) return false;
      if (Signature != other.Signature) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (header_ != null) hash ^= Header.GetHashCode();
      if (EncryptedPayload.Length != 0) hash ^= EncryptedPayload.GetHashCode();
      if (Signature.Length != 0) hash ^= Signature.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      if (EncryptedPayload.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(EncryptedPayload);
      }
      if (Signature.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(Signature);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      if (EncryptedPayload.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(EncryptedPayload);
      }
      if (Signature.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(Signature);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (header_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Header);
      }
      if (EncryptedPayload.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(EncryptedPayload);
      }
      if (Signature.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Signature);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MeshPacket other) {
      if (other == null) {
        return;
      }
      if (other.header_ != null) {
        if (header_ == null) {
          Header = new global::Afet.Mesh.Header();
        }
        Header.MergeFrom(other.Header);
      }
      if (other.EncryptedPayload.Length != 0) {
        EncryptedPayload = other.EncryptedPayload;
      }
      if (other.Signature.Length != 0) {
        Signature = other.Signature;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (header_ == null) {
              Header = new global::Afet.Mesh.Header();
            }
            input.ReadMessage(Header);
            break;
          }
          case 18: {
            EncryptedPayload = input.ReadBytes();
            break;
          }
          case 26: {
            Signature = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (header_ == null) {
              Header = new global::Afet.Mesh.Header();
            }
            input.ReadMessage(Header);
            break;
          }
          case 18: {
            EncryptedPayload = input.ReadBytes();
            break;
          }
          case 26: {
            Signature = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// ─────────────────────────────────────────────────────────────────────
  /// YÖNLENDIRME BAŞLIĞI — TTL, Öncelik, Rota, Enkaz Tanımı
  /// ─────────────────────────────────────────────────────────────────────
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Header : pb::IMessage<Header>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Header> _parser = new pb::MessageParser<Header>(() => new Header());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Header> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Afet.Mesh.MeshPacketReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Header() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Header(Header other) : this() {
      messageId_ = other.messageId_;
      timestampEpoch_ = other.timestampEpoch_;
      ttl_ = other.ttl_;
      hopCount_ = other.hopCount_;
      packetType_ = other.packetType_;
      senderPublicKey_ = other.senderPublicKey_;
      recipientPublicKey_ = other.recipientPublicKey_;
      payloadLength_ = other.payloadLength_;
      hopTrace_ = other.hopTrace_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Header Clone() {
      return new Header(this);
    }

    /// <summary>Field number for the "message_id" field.</summary>
    public const int MessageIdFieldNumber = 1;
    private pb::ByteString messageId_ = pb::ByteString.Empty;
    /// <summary>
    /// 12 byte: Paketin evrensel benzersiz kimliği (deduplication için)
    /// Küçük tutulmuş: UUID'nin ilk 12 baytı, hex yerine binary.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString MessageId {
      get { return messageId_; }
      set {
        messageId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "timestamp_epoch" field.</summary>
    public const int TimestampEpochFieldNumber = 2;
    private uint timestampEpoch_;
    /// <summary>
    /// Epoch saniye cinsinden zaman damgası (4 byte - uint32)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint TimestampEpoch {
      get { return timestampEpoch_; }
      set {
        timestampEpoch_ = value;
      }
    }

    /// <summary>Field number for the "ttl" field.</summary>
    public const int TtlFieldNumber = 3;
    private uint ttl_;
    /// <summary>
    /// Kaç cihazdan daha atlanabilir? Her hop'ta 1 azalır. 0 ise düşürülür.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Ttl {
      get { return ttl_; }
      set {
        ttl_ = value;
      }
    }

    /// <summary>Field number for the "hop_count" field.</summary>
    public const int HopCountFieldNumber = 4;
    private uint hopCount_;
    /// <summary>
    /// Kaçıncı hop'tayız? (İzleme/analiz için)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint HopCount {
      get { return hopCount_; }
      set {
        hopCount_ = value;
      }
    }

    /// <summary>Field number for the "packet_type" field.</summary>
    public const int PacketTypeFieldNumber = 5;
    private global::Afet.Mesh.PacketType packetType_ = global::Afet.Mesh.PacketType.Unknown;
    /// <summary>
    /// Mesaj tipi / öncelik sınıfı
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Afet.Mesh.PacketType PacketType {
      get { return packetType_; }
      set {
        packetType_ = value;
      }
    }

    /// <summary>Field number for the "sender_public_key" field.</summary>
    public const int SenderPublicKeyFieldNumber = 6;
    private pb::ByteString senderPublicKey_ = pb::ByteString.Empty;
    /// <summary>
    /// Paketi üreten cihazın Ed25519 Genel Anahtarı (32 byte)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString SenderPublicKey {
      get { return senderPublicKey_; }
      set {
        senderPublicKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "recipient_public_key" field.</summary>
    public const int RecipientPublicKeyFieldNumber = 7;
    private pb::ByteString recipientPublicKey_ = pb::ByteString.Empty;
    /// <summary>
    /// Kurtarma merkezinin Curve25519 Alıcı Genel Anahtarı (32 byte)
    /// (Bu anahtar ile encrypted_payload şifrelenmiştir)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString RecipientPublicKey {
      get { return recipientPublicKey_; }
      set {
        recipientPublicKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "payload_length" field.</summary>
    public const int PayloadLengthFieldNumber = 8;
    private uint payloadLength_;
    /// <summary>
    /// Enkripteli yük boyutu (bytes cinsinden)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint PayloadLength {
      get { return payloadLength_; }
      set {
        payloadLength_ = value;
      }
    }

    /// <summary>Field number for the "hop_trace" field.</summary>
    public const int HopTraceFieldNumber = 9;
    private static readonly pb::FieldCodec<pb::ByteString> _repeated_hopTrace_codec
        = pb::FieldCodec.ForBytes(74);
    private readonly pbc::RepeatedField<pb::ByteString> hopTrace_ = new pbc::RepeatedField<pb::ByteString>();
    /// <summary>
    /// Paketin geçtiği cihazların kısa kimlikleri (sıçrama zinciri izleme, max 10x6=60 byte)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<pb::ByteString> HopTrace {
      get { return hopTrace_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Header);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Header other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MessageId != other.MessageId) return false;
      if (TimestampEpoch != other.TimestampEpoch) return false;
      if (Ttl != other.Ttl) return false;
      if (HopCount != other.HopCount) return false;
      if (PacketType != other.PacketType) return false;
      if (SenderPublicKey != other.SenderPublicKey) return false;
      if (RecipientPublicKey != other.RecipientPublicKey) return false;
      if (PayloadLength != other.PayloadLength) return false;
      if(!hopTrace_.Equals(other.hopTrace_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MessageId.Length != 0) hash ^= MessageId.GetHashCode();
      if (TimestampEpoch != 0) hash ^= TimestampEpoch.GetHashCode();
      if (Ttl != 0) hash ^= Ttl.GetHashCode();
      if (HopCount != 0) hash ^= HopCount.GetHashCode();
      if (PacketType != global::Afet.Mesh.PacketType.Unknown) hash ^= PacketType.GetHashCode();
      if (SenderPublicKey.Length != 0) hash ^= SenderPublicKey.GetHashCode();
      if (RecipientPublicKey.Length != 0) hash ^= RecipientPublicKey.GetHashCode();
      if (PayloadLength != 0) hash ^= PayloadLength.GetHashCode();
      hash ^= hopTrace_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MessageId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(MessageId);
      }
      if (TimestampEpoch != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(TimestampEpoch);
      }
      if (Ttl != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Ttl);
      }
      if (HopCount != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(HopCount);
      }
      if (PacketType != global::Afet.Mesh.PacketType.Unknown) {
        output.WriteRawTag(40);
        output.WriteEnum((int) PacketType);
      }
      if (SenderPublicKey.Length != 0) {
        output.WriteRawTag(50);
        output.WriteBytes(SenderPublicKey);
      }
      if (RecipientPublicKey.Length != 0) {
        output.WriteRawTag(58);
        output.WriteBytes(RecipientPublicKey);
      }
      if (PayloadLength != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(PayloadLength);
      }
      hopTrace_.WriteTo(output, _repeated_hopTrace_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MessageId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(MessageId);
      }
      if (TimestampEpoch != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(TimestampEpoch);
      }
      if (Ttl != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Ttl);
      }
      if (HopCount != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(HopCount);
      }
      if (PacketType != global::Afet.Mesh.PacketType.Unknown) {
        output.WriteRawTag(40);
        output.WriteEnum((int) PacketType);
      }
      if (SenderPublicKey.Length != 0) {
        output.WriteRawTag(50);
        output.WriteBytes(SenderPublicKey);
      }
      if (RecipientPublicKey.Length != 0) {
        output.WriteRawTag(58);
        output.WriteBytes(RecipientPublicKey);
      }
      if (PayloadLength != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(PayloadLength);
      }
      hopTrace_.WriteTo(ref output, _repeated_hopTrace_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MessageId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(MessageId);
      }
      if (TimestampEpoch != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(TimestampEpoch);
      }
      if (Ttl != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Ttl);
      }
      if (HopCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(HopCount);
      }
      if (PacketType != global::Afet.Mesh.PacketType.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) PacketType);
      }
      if (SenderPublicKey.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(SenderPublicKey);
      }
      if (RecipientPublicKey.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(RecipientPublicKey);
      }
      if (PayloadLength != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PayloadLength);
      }
      size += hopTrace_.CalculateSize(_repeated_hopTrace_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Header other) {
      if (other == null) {
        return;
      }
      if (other.MessageId.Length != 0) {
        MessageId = other.MessageId;
      }
      if (other.TimestampEpoch != 0) {
        TimestampEpoch = other.TimestampEpoch;
      }
      if (other.Ttl != 0) {
        Ttl = other.Ttl;
      }
      if (other.HopCount != 0) {
        HopCount = other.HopCount;
      }
      if (other.PacketType != global::Afet.Mesh.PacketType.Unknown) {
        PacketType = other.PacketType;
      }
      if (other.SenderPublicKey.Length != 0) {
        SenderPublicKey = other.SenderPublicKey;
      }
      if (other.RecipientPublicKey.Length != 0) {
        RecipientPublicKey = other.RecipientPublicKey;
      }
      if (other.PayloadLength != 0) {
        PayloadLength = other.PayloadLength;
      }
      hopTrace_.Add(other.hopTrace_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            MessageId = input.ReadBytes();
            break;
          }
          case 16: {
            TimestampEpoch = input.ReadUInt32();
            break;
          }
          case 24: {
            Ttl = input.ReadUInt32();
            break;
          }
          case 32: {
            HopCount = input.ReadUInt32();
            break;
          }
          case 40: {
            PacketType = (global::Afet.Mesh.PacketType) input.ReadEnum();
            break;
          }
          case 50: {
            SenderPublicKey = input.ReadBytes();
            break;
          }
          case 58: {
            RecipientPublicKey = input.ReadBytes();
            break;
          }
          case 64: {
            PayloadLength = input.ReadUInt32();
            break;
          }
          case 74: {
            hopTrace_.AddEntriesFrom(input, _repeated_hopTrace_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            MessageId = input.ReadBytes();
            break;
          }
          case 16: {
            TimestampEpoch = input.ReadUInt32();
            break;
          }
          case 24: {
            Ttl = input.ReadUInt32();
            break;
          }
          case 32: {
            HopCount = input.ReadUInt32();
            break;
          }
          case 40: {
            PacketType = (global::Afet.Mesh.PacketType) input.ReadEnum();
            break;
          }
          case 50: {
            SenderPublicKey = input.ReadBytes();
            break;
          }
          case 58: {
            RecipientPublicKey = input.ReadBytes();
            break;
          }
          case 64: {
            PayloadLength = input.ReadUInt32();
            break;
          }
          case 74: {
            hopTrace_.AddEntriesFrom(ref input, _repeated_hopTrace_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// ─────────────────────────────────────────────────────────────────────
  /// ŞİFRELENMİŞ YÜK İÇİNDEKİ VERİ (Sadece kurtarma merkezi okuyabilir)
  /// Bu mesaj Protobuf ile serileştirildikten sonra Curve25519 ile şifrelenir.
  /// ─────────────────────────────────────────────────────────────────────
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class EmergencyPayload : pb::IMessage<EmergencyPayload>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EmergencyPayload> _parser = new pb::MessageParser<EmergencyPayload>(() => new EmergencyPayload());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EmergencyPayload> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Afet.Mesh.MeshPacketReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EmergencyPayload() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EmergencyPayload(EmergencyPayload other) : this() {
      latitudeE6_ = other.latitudeE6_;
      longitudeE6_ = other.longitudeE6_;
      accuracyM_ = other.accuracyM_;
      altitudeM_ = other.altitudeM_;
      isTrapped_ = other.isTrapped_;
      isInjured_ = other.isInjured_;
      isConscious_ = other.isConscious_;
      peopleCount_ = other.peopleCount_;
      batteryPct_ = other.batteryPct_;
      messageText_ = other.messageText_;
      bloodType_ = other.bloodType_;
      medicalNotes_ = other.medicalNotes_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EmergencyPayload Clone() {
      return new EmergencyPayload(this);
    }

    /// <summary>Field number for the "latitude_e6" field.</summary>
    public const int LatitudeE6FieldNumber = 1;
    private int latitudeE6_;
    /// <summary>
    /// ── Konum ──
    /// Enlem x 1e6 (ör. 41°01'30" N → 41001500)  — 4 byte int32, ~10cm hassasiyet
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int LatitudeE6 {
      get { return latitudeE6_; }
      set {
        latitudeE6_ = value;
      }
    }

    /// <summary>Field number for the "longitude_e6" field.</summary>
    public const int LongitudeE6FieldNumber = 2;
    private int longitudeE6_;
    /// <summary>
    /// Boylam x 1e6                               — 4 byte int32
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int LongitudeE6 {
      get { return longitudeE6_; }
      set {
        longitudeE6_ = value;
      }
    }

    /// <summary>Field number for the "accuracy_m" field.</summary>
    public const int AccuracyMFieldNumber = 3;
    private uint accuracyM_;
    /// <summary>
    /// GPS hassasiyet yarıçapı (metre, 0-255)     — 1 byte
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint AccuracyM {
      get { return accuracyM_; }
      set {
        accuracyM_ = value;
      }
    }

    /// <summary>Field number for the "altitude_m" field.</summary>
    public const int AltitudeMFieldNumber = 4;
    private int altitudeM_;
    /// <summary>
    /// Rakım (metre, -500 ile +8500)              — 2 byte int32
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int AltitudeM {
      get { return altitudeM_; }
      set {
        altitudeM_ = value;
      }
    }

    /// <summary>Field number for the "is_trapped" field.</summary>
    public const int IsTrappedFieldNumber = 5;
    private bool isTrapped_;
    /// <summary>
    /// ── Durum Bitleri ──
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsTrapped {
      get { return isTrapped_; }
      set {
        isTrapped_ = value;
      }
    }

    /// <summary>Field number for the "is_injured" field.</summary>
    public const int IsInjuredFieldNumber = 6;
    private bool isInjured_;
    /// <summary>
    /// En az 1 kişi yaralı
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsInjured {
      get { return isInjured_; }
      set {
        isInjured_ = value;
      }
    }

    /// <summary>Field number for the "is_conscious" field.</summary>
    public const int IsConsciousFieldNumber = 7;
    private bool isConscious_;
    /// <summary>
    /// Bilinç açık
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsConscious {
      get { return isConscious_; }
      set {
        isConscious_ = value;
      }
    }

    /// <summary>Field number for the "people_count" field.</summary>
    public const int PeopleCountFieldNumber = 8;
    private uint peopleCount_;
    /// <summary>
    /// Toplam kişi sayısı (0-15 → 4 bit, uint32 olarak saklı)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint PeopleCount {
      get { return peopleCount_; }
      set {
        peopleCount_ = value;
      }
    }

    /// <summary>Field number for the "battery_pct" field.</summary>
    public const int BatteryPctFieldNumber = 9;
    private uint batteryPct_;
    /// <summary>
    /// Pil yüzdesi %0-100
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint BatteryPct {
      get { return batteryPct_; }
      set {
        batteryPct_ = value;
      }
    }

    /// <summary>Field number for the "message_text" field.</summary>
    public const int MessageTextFieldNumber = 10;
    private string messageText_ = "";
    /// <summary>
    /// ── Serbest Metin ──
    /// Max 64 UTF-8 byte (UTF-8 Türkçe karakterler için 1-2 byte/karakter)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MessageText {
      get { return messageText_; }
      set {
        messageText_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "blood_type" field.</summary>
    public const int BloodTypeFieldNumber = 11;
    private string bloodType_ = "";
    /// <summary>
    /// ── Tıbbi Acil ──
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string BloodType {
      get { return bloodType_; }
      set {
        bloodType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "medical_notes" field.</summary>
    public const int MedicalNotesFieldNumber = 12;
    private string medicalNotes_ = "";
    /// <summary>
    /// "Diyabetik, insülin gerekiyor" (max 48 byte)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MedicalNotes {
      get { return medicalNotes_; }
      set {
        medicalNotes_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EmergencyPayload);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EmergencyPayload other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LatitudeE6 != other.LatitudeE6) return false;
      if (LongitudeE6 != other.LongitudeE6) return false;
      if (AccuracyM != other.AccuracyM) return false;
      if (AltitudeM != other.AltitudeM) return false;
      if (IsTrapped != other.IsTrapped) return false;
      if (IsInjured != other.IsInjured) return false;
      if (IsConscious != other.IsConscious) return false;
      if (PeopleCount != other.PeopleCount) return false;
      if (BatteryPct != other.BatteryPct) return false;
      if (MessageText != other.MessageText) return false;
      if (BloodType != other.BloodType) return false;
      if (MedicalNotes != other.MedicalNotes) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (LatitudeE6 != 0) hash ^= LatitudeE6.GetHashCode();
      if (LongitudeE6 != 0) hash ^= LongitudeE6.GetHashCode();
      if (AccuracyM != 0) hash ^= AccuracyM.GetHashCode();
      if (AltitudeM != 0) hash ^= AltitudeM.GetHashCode();
      if (IsTrapped != false) hash ^= IsTrapped.GetHashCode();
      if (IsInjured != false) hash ^= IsInjured.GetHashCode();
      if (IsConscious != false) hash ^= IsConscious.GetHashCode();
      if (PeopleCount != 0) hash ^= PeopleCount.GetHashCode();
      if (BatteryPct != 0) hash ^= BatteryPct.GetHashCode();
      if (MessageText.Length != 0) hash ^= MessageText.GetHashCode();
      if (BloodType.Length != 0) hash ^= BloodType.GetHashCode();
      if (MedicalNotes.Length != 0) hash ^= MedicalNotes.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (LatitudeE6 != 0) {
        output.WriteRawTag(8);
        output.WriteSInt32(LatitudeE6);
      }
      if (LongitudeE6 != 0) {
        output.WriteRawTag(16);
        output.WriteSInt32(LongitudeE6);
      }
      if (AccuracyM != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(AccuracyM);
      }
      if (AltitudeM != 0) {
        output.WriteRawTag(32);
        output.WriteSInt32(AltitudeM);
      }
      if (IsTrapped != false) {
        output.WriteRawTag(40);
        output.WriteBool(IsTrapped);
      }
      if (IsInjured != false) {
        output.WriteRawTag(48);
        output.WriteBool(IsInjured);
      }
      if (IsConscious != false) {
        output.WriteRawTag(56);
        output.WriteBool(IsConscious);
      }
      if (PeopleCount != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(PeopleCount);
      }
      if (BatteryPct != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(BatteryPct);
      }
      if (MessageText.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(MessageText);
      }
      if (BloodType.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(BloodType);
      }
      if (MedicalNotes.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(MedicalNotes);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (LatitudeE6 != 0) {
        output.WriteRawTag(8);
        output.WriteSInt32(LatitudeE6);
      }
      if (LongitudeE6 != 0) {
        output.WriteRawTag(16);
        output.WriteSInt32(LongitudeE6);
      }
      if (AccuracyM != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(AccuracyM);
      }
      if (AltitudeM != 0) {
        output.WriteRawTag(32);
        output.WriteSInt32(AltitudeM);
      }
      if (IsTrapped != false) {
        output.WriteRawTag(40);
        output.WriteBool(IsTrapped);
      }
      if (IsInjured != false) {
        output.WriteRawTag(48);
        output.WriteBool(IsInjured);
      }
      if (IsConscious != false) {
        output.WriteRawTag(56);
        output.WriteBool(IsConscious);
      }
      if (PeopleCount != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(PeopleCount);
      }
      if (BatteryPct != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(BatteryPct);
      }
      if (MessageText.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(MessageText);
      }
      if (BloodType.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(BloodType);
      }
      if (MedicalNotes.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(MedicalNotes);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (LatitudeE6 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeSInt32Size(LatitudeE6);
      }
      if (LongitudeE6 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeSInt32Size(LongitudeE6);
      }
      if (AccuracyM != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(AccuracyM);
      }
      if (AltitudeM != 0) {
        size += 1 + pb::CodedOutputStream.ComputeSInt32Size(AltitudeM);
      }
      if (IsTrapped != false) {
        size += 1 + 1;
      }
      if (IsInjured != false) {
        size += 1 + 1;
      }
      if (IsConscious != false) {
        size += 1 + 1;
      }
      if (PeopleCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PeopleCount);
      }
      if (BatteryPct != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(BatteryPct);
      }
      if (MessageText.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MessageText);
      }
      if (BloodType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BloodType);
      }
      if (MedicalNotes.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MedicalNotes);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EmergencyPayload other) {
      if (other == null) {
        return;
      }
      if (other.LatitudeE6 != 0) {
        LatitudeE6 = other.LatitudeE6;
      }
      if (other.LongitudeE6 != 0) {
        LongitudeE6 = other.LongitudeE6;
      }
      if (other.AccuracyM != 0) {
        AccuracyM = other.AccuracyM;
      }
      if (other.AltitudeM != 0) {
        AltitudeM = other.AltitudeM;
      }
      if (other.IsTrapped != false) {
        IsTrapped = other.IsTrapped;
      }
      if (other.IsInjured != false) {
        IsInjured = other.IsInjured;
      }
      if (other.IsConscious != false) {
        IsConscious = other.IsConscious;
      }
      if (other.PeopleCount != 0) {
        PeopleCount = other.PeopleCount;
      }
      if (other.BatteryPct != 0) {
        BatteryPct = other.BatteryPct;
      }
      if (other.MessageText.Length != 0) {
        MessageText = other.MessageText;
      }
      if (other.BloodType.Length != 0) {
        BloodType = other.BloodType;
      }
      if (other.MedicalNotes.Length != 0) {
        MedicalNotes = other.MedicalNotes;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            LatitudeE6 = input.ReadSInt32();
            break;
          }
          case 16: {
            LongitudeE6 = input.ReadSInt32();
            break;
          }
          case 24: {
            AccuracyM = input.ReadUInt32();
            break;
          }
          case 32: {
            AltitudeM = input.ReadSInt32();
            break;
          }
          case 40: {
            IsTrapped = input.ReadBool();
            break;
          }
          case 48: {
            IsInjured = input.ReadBool();
            break;
          }
          case 56: {
            IsConscious = input.ReadBool();
            break;
          }
          case 64: {
            PeopleCount = input.ReadUInt32();
            break;
          }
          case 72: {
            BatteryPct = input.ReadUInt32();
            break;
          }
          case 82: {
            MessageText = input.ReadString();
            break;
          }
          case 90: {
            BloodType = input.ReadString();
            break;
          }
          case 98: {
            MedicalNotes = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            LatitudeE6 = input.ReadSInt32();
            break;
          }
          case 16: {
            LongitudeE6 = input.ReadSInt32();
            break;
          }
          case 24: {
            AccuracyM = input.ReadUInt32();
            break;
          }
          case 32: {
            AltitudeM = input.ReadSInt32();
            break;
          }
          case 40: {
            IsTrapped = input.ReadBool();
            break;
          }
          case 48: {
            IsInjured = input.ReadBool();
            break;
          }
          case 56: {
            IsConscious = input.ReadBool();
            break;
          }
          case 64: {
            PeopleCount = input.ReadUInt32();
            break;
          }
          case 72: {
            BatteryPct = input.ReadUInt32();
            break;
          }
          case 82: {
            MessageText = input.ReadString();
            break;
          }
          case 90: {
            BloodType = input.ReadString();
            break;
          }
          case 98: {
            MedicalNotes = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// ─────────────────────────────────────────────────────────────────────
  /// ANTİ-ENTROPİ / ENVANTER TAKAS PAKETI
  /// İki cihaz karşılaştığında önce sahip oldukları mesaj ID'lerini paylaşır.
  /// Bu sayede sadece eksik olanlar aktarılır; gereksiz bant genişliği kullanılmaz.
  /// ─────────────────────────────────────────────────────────────────────
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AntiEntropyDigest : pb::IMessage<AntiEntropyDigest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AntiEntropyDigest> _parser = new pb::MessageParser<AntiEntropyDigest>(() => new AntiEntropyDigest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AntiEntropyDigest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Afet.Mesh.MeshPacketReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AntiEntropyDigest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AntiEntropyDigest(AntiEntropyDigest other) : this() {
      knownMessageIds_ = other.knownMessageIds_.Clone();
      hasGatewayConnection_ = other.hasGatewayConnection_;
      senderNodeId_ = other.senderNodeId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AntiEntropyDigest Clone() {
      return new AntiEntropyDigest(this);
    }

    /// <summary>Field number for the "known_message_ids" field.</summary>
    public const int KnownMessageIdsFieldNumber = 1;
    private static readonly pb::FieldCodec<pb::ByteString> _repeated_knownMessageIds_codec
        = pb::FieldCodec.ForBytes(10);
    private readonly pbc::RepeatedField<pb::ByteString> knownMessageIds_ = new pbc::RepeatedField<pb::ByteString>();
    /// <summary>
    /// Cihazın sahip olduğu message_id'lerin kompakt listesi
    /// 12 byte × N ID = bant genişliği dostu envanter
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<pb::ByteString> KnownMessageIds {
      get { return knownMessageIds_; }
    }

    /// <summary>Field number for the "has_gateway_connection" field.</summary>
    public const int HasGatewayConnectionFieldNumber = 2;
    private bool hasGatewayConnection_;
    /// <summary>
    /// Bu cihaz bir kurtarma merkezine bağlanabildi mi?
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasGatewayConnection {
      get { return hasGatewayConnection_; }
      set {
        hasGatewayConnection_ = value;
      }
    }

    /// <summary>Field number for the "sender_node_id" field.</summary>
    public const int SenderNodeIdFieldNumber = 3;
    private pb::ByteString senderNodeId_ = pb::ByteString.Empty;
    /// <summary>
    /// Bu digest'i gönderen cihazın kısa kimliği (6 byte)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString SenderNodeId {
      get { return senderNodeId_; }
      set {
        senderNodeId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AntiEntropyDigest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AntiEntropyDigest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!knownMessageIds_.Equals(other.knownMessageIds_)) return false;
      if (HasGatewayConnection != other.HasGatewayConnection) return false;
      if (SenderNodeId != other.SenderNodeId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= knownMessageIds_.GetHashCode();
      if (HasGatewayConnection != false) hash ^= HasGatewayConnection.GetHashCode();
      if (SenderNodeId.Length != 0) hash ^= SenderNodeId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      knownMessageIds_.WriteTo(output, _repeated_knownMessageIds_codec);
      if (HasGatewayConnection != false) {
        output.WriteRawTag(16);
        output.WriteBool(HasGatewayConnection);
      }
      if (SenderNodeId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(SenderNodeId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      knownMessageIds_.WriteTo(ref output, _repeated_knownMessageIds_codec);
      if (HasGatewayConnection != false) {
        output.WriteRawTag(16);
        output.WriteBool(HasGatewayConnection);
      }
      if (SenderNodeId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(SenderNodeId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += knownMessageIds_.CalculateSize(_repeated_knownMessageIds_codec);
      if (HasGatewayConnection != false) {
        size += 1 + 1;
      }
      if (SenderNodeId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(SenderNodeId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AntiEntropyDigest other) {
      if (other == null) {
        return;
      }
      knownMessageIds_.Add(other.knownMessageIds_);
      if (other.HasGatewayConnection != false) {
        HasGatewayConnection = other.HasGatewayConnection;
      }
      if (other.SenderNodeId.Length != 0) {
        SenderNodeId = other.SenderNodeId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            knownMessageIds_.AddEntriesFrom(input, _repeated_knownMessageIds_codec);
            break;
          }
          case 16: {
            HasGatewayConnection = input.ReadBool();
            break;
          }
          case 26: {
            SenderNodeId = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            knownMessageIds_.AddEntriesFrom(ref input, _repeated_knownMessageIds_codec);
            break;
          }
          case 16: {
            HasGatewayConnection = input.ReadBool();
            break;
          }
          case 26: {
            SenderNodeId = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// ─────────────────────────────────────────────────────────────────────
  /// ACK / TESLİMAT ONAY PAKETİ
  /// Kurtarma merkezi paketi aldığında ağa geriye doğru yayar.
  /// Ara cihazlar bu ID'yi görünce belleklerindeki kopyayı siler.
  /// ─────────────────────────────────────────────────────────────────────
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AckPacket : pb::IMessage<AckPacket>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AckPacket> _parser = new pb::MessageParser<AckPacket>(() => new AckPacket());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AckPacket> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Afet.Mesh.MeshPacketReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AckPacket() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AckPacket(AckPacket other) : this() {
      ackedMessageId_ = other.ackedMessageId_;
      gatewayNodeId_ = other.gatewayNodeId_;
      deliveryHopCount_ = other.deliveryHopCount_;
      estimatedRescueEpoch_ = other.estimatedRescueEpoch_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AckPacket Clone() {
      return new AckPacket(this);
    }

    /// <summary>Field number for the "acked_message_id" field.</summary>
    public const int AckedMessageIdFieldNumber = 1;
    private pb::ByteString ackedMessageId_ = pb::ByteString.Empty;
    /// <summary>
    /// Hangi mesaj başarıyla teslim alındı?
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString AckedMessageId {
      get { return ackedMessageId_; }
      set {
        ackedMessageId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "gateway_node_id" field.</summary>
    public const int GatewayNodeIdFieldNumber = 2;
    private pb::ByteString gatewayNodeId_ = pb::ByteString.Empty;
    /// <summary>
    /// Kurtarma merkezinin kimliği (Gateway Node ID)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString GatewayNodeId {
      get { return gatewayNodeId_; }
      set {
        gatewayNodeId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "delivery_hop_count" field.</summary>
    public const int DeliveryHopCountFieldNumber = 3;
    private uint deliveryHopCount_;
    /// <summary>
    /// Kaç cihaz zinciri üzerinden ulaştı? (İstatistik)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint DeliveryHopCount {
      get { return deliveryHopCount_; }
      set {
        deliveryHopCount_ = value;
      }
    }

    /// <summary>Field number for the "estimated_rescue_epoch" field.</summary>
    public const int EstimatedRescueEpochFieldNumber = 4;
    private uint estimatedRescueEpoch_;
    /// <summary>
    /// Kurtarma ekibinin tahmini varış zamanı (Unix epoch, 0 ise bilinmiyor)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint EstimatedRescueEpoch {
      get { return estimatedRescueEpoch_; }
      set {
        estimatedRescueEpoch_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AckPacket);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AckPacket other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AckedMessageId != other.AckedMessageId) return false;
      if (GatewayNodeId != other.GatewayNodeId) return false;
      if (DeliveryHopCount != other.DeliveryHopCount) return false;
      if (EstimatedRescueEpoch != other.EstimatedRescueEpoch) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (AckedMessageId.Length != 0) hash ^= AckedMessageId.GetHashCode();
      if (GatewayNodeId.Length != 0) hash ^= GatewayNodeId.GetHashCode();
      if (DeliveryHopCount != 0) hash ^= DeliveryHopCount.GetHashCode();
      if (EstimatedRescueEpoch != 0) hash ^= EstimatedRescueEpoch.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (AckedMessageId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(AckedMessageId);
      }
      if (GatewayNodeId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(GatewayNodeId);
      }
      if (DeliveryHopCount != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(DeliveryHopCount);
      }
      if (EstimatedRescueEpoch != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(EstimatedRescueEpoch);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (AckedMessageId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(AckedMessageId);
      }
      if (GatewayNodeId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(GatewayNodeId);
      }
      if (DeliveryHopCount != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(DeliveryHopCount);
      }
      if (EstimatedRescueEpoch != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(EstimatedRescueEpoch);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (AckedMessageId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(AckedMessageId);
      }
      if (GatewayNodeId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(GatewayNodeId);
      }
      if (DeliveryHopCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DeliveryHopCount);
      }
      if (EstimatedRescueEpoch != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(EstimatedRescueEpoch);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AckPacket other) {
      if (other == null) {
        return;
      }
      if (other.AckedMessageId.Length != 0) {
        AckedMessageId = other.AckedMessageId;
      }
      if (other.GatewayNodeId.Length != 0) {
        GatewayNodeId = other.GatewayNodeId;
      }
      if (other.DeliveryHopCount != 0) {
        DeliveryHopCount = other.DeliveryHopCount;
      }
      if (other.EstimatedRescueEpoch != 0) {
        EstimatedRescueEpoch = other.EstimatedRescueEpoch;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            AckedMessageId = input.ReadBytes();
            break;
          }
          case 18: {
            GatewayNodeId = input.ReadBytes();
            break;
          }
          case 24: {
            DeliveryHopCount = input.ReadUInt32();
            break;
          }
          case 32: {
            EstimatedRescueEpoch = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            AckedMessageId = input.ReadBytes();
            break;
          }
          case 18: {
            GatewayNodeId = input.ReadBytes();
            break;
          }
          case 24: {
            DeliveryHopCount = input.ReadUInt32();
            break;
          }
          case 32: {
            EstimatedRescueEpoch = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
